---
# tasks file for k8s_addons
#- name: Copy templates to remote host
#  template:
#    src: "{{ item }}"
#    dest: "/tmp/{{ item }}"
#  with_items: "{{ k8s_addons }}"
- name: Generate local deployment dir
  file:
    path: "{{ localdeploydir }}"
    state: directory
    mode: 0777
  delegate_to: 127.0.0.1
  
- name: Copy templates to local deployment dir
  template:
    src: "{{ item }}"
    dest: "{{ localdeploydir }}/{{ item }}"
  with_items: "{{ k8s_addons }}"
  delegate_to: 127.0.0.1
